config/routes.rb
require 'api'
Todoro::Application.routes.draw do
  resources :tasks, :only => [:index, :new, :create, :update, :destroy]

  root :to => 'welcome#index'
  
  mount Todoro::API => "/api"

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true, :length => {:maximum => 140}

  def done!
    self.done = true
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :find_task, :only => [:update, :destroy]
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to({:action => "index"}, notice: 'Task was successfully created.') }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.json { head :ok }
      else
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end

  private
  def find_task
    @task = Task.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def brand_logo
    link_to(image_tag("brand.png"), root_path, :class => "brand")
  end

  def head_tags
    capture_haml do
      haml_tag :title, @title || "ToDoRo - ToDo Application"
      haml_tag :link, :href => "/apple-touch-icon.png", :rel => "apple-touch-icon"
      haml_tag :meta, :name => "viewport", :content => "width=device-width, initial-scale=1.0, maximum-scale=0.6667, user-scalable=0;" 
    end
  end

  def footer_content
    capture_haml do
      haml_tag :p, %Q{&copy; Takumi MIURA 2011}.html_safe
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = head_tags
    = stylesheet_link_tag "application"
    = csrf_meta_tags
  %body
    .topbar
      .topbar-inner
        .container-fluid
          = brand_logo
          = tabs
    .container
      .content
        = yield
      %footer= footer_content
    .javascripts
      = javascript_include_tag "application"

app/views/tasks/_form.html.haml
= semantic_form_for @task do |f|
  = f.inputs do
    = f.input :name
  
  = f.buttons do
    = f.commit_button :button_html => {:class => "primary"}

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %tr
    %th Name
    %th Done
    %th Finished at
    %th

  - @tasks.each do |task|
    %tr
      %td= best_in_place task, :name
      %td= task.done
      %td= task.finished_at
      %td= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/welcome/index.html.haml
.top_logo= image_tag "logo.png"